#!/bin/sh

export NODE_PATH
NODE_PATH=/usr/local/lib/node_modules

export BIND_ADDR_FILE
BIND_ADDR_FILE=/tmp/pvd-add

/bin/rm -f $BIND_ADDR_FILE

ps auxww |
grep pvdHttpServer.js |
grep node |
awk '{print $2}' |
while read p
do
	kill $p
done

node `dirname $0`/pvdHttpServer.js -f `dirname $0`/CaptivePortal.html >/dev/null 2>&1 &

ps auxww |
grep DetectCaptivePortal.js |
grep node | 
awk '{print $2}' |
while read p
do
	kill $p
done

sleep 1

exec node `dirname $0`/DetectCaptivePortal.js "$@"
